import createClient from 'openapi-fetch';
import env from '#env';
import type { paths } from '#/__generated__/paymentApi'; // generated by openapi-typescript

const client = createClient<paths>({
  baseUrl: env.PAYMENT_API_URL,
  headers: {
    'Content-Type': 'application/ld+json',
    Accept: 'application/ld+json',
  },
});

export default client;
