/**
 * Errors that the API may return in case of invalid call.
 */
const ERRORS = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONENUMBER_ALREADY_EXISTS: 'PHONENUMBER_ALREADY_EXISTS',
  EMAIL_NOT_VALID: 'EMAIL_NOT_VALID',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  UNAUTORIZED: 'UNAUTORIZED',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTORIZED_INVALID_ACCESS_TOKEN: 'UNAUTORIZED_INVALID_ACCESS_TOKEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  JSON_DECODING_ERROR: 'JSON_DECODING_ERROR',
  BLOB_DECODING_ERROR: 'BLOB_DECODING_ERROR',
  GRAPHQL_ERROR: 'GRAPHQL_ERROR',
} as const;

export default ERRORS;
