/**
 * List of fonts that are supported by the application and can be used in
 * the cover and module editors.
 */
export const APPLICATIONS_FONTS = [
  'Anton_Regular',
  'Archivo_Black',
  'Archivo_Light',
  'Cinzel_Regular',
  'CourrierPrime_Regular',
  'DMSerifDisplay_Regular',
  'FaunaOne_Regular',
  'Fraunces_Light',
  'GreatVibes_Regular',
  'Inter_Regular',
  'Inter_Medium',
  'Inter_SemiBold',
  'Inter_Black',
  'JosefinSans_Regular',
  'Jost_Regular',
  'Kaushan_Regular',
  'Koulen_Regular',
  'LibreCaslonText_Regular',
  'Limelight_Regular',
  'Lora_Regular',
  'Lora_Bold',
  'Manrope_ExtraLight',
  'Manrope_Light',
  'Manrope_Regular',
  'Monoton_Regular',
  'Montserrat_Regular',
  'Montserrat_SemiBold',
  'MrDafoe_Regular',
  'OpenSans_Regular',
  'PlayfairDisplay_Bold',
  'Plus-Jakarta_Light',
  'Plus-Jakarta_ExtraBold',
  'Poppins_Regular',
  'Poppins_SemiBold',
  'Poppins_Bold',
  'Poppins_Black',
  'Raleway_Regular',
  'Righteous_Regular',
  'Rye_Regular',
  'SeaweedScript_Regular',
  'SourcePro_Regular',
  'YesevaOne_Regular',
] as const;

export type ApplicationFonts = (typeof APPLICATIONS_FONTS)[number];
