/**
 * Errors that the API may return in case of invalid call.
 */
const ERRORS = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  UNAUTORIZED: 'UNAUTORIZED',
  UNAUTORIZED_INVALID_ACCESS_TOKEN: 'UNAUTORIZED_INVALID_ACCESS_TOKEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  JSON_DECODING_ERROR: 'JSON_DECODING_ERROR',
} as const;

export default ERRORS;
