name: Pull translations
description: Pull translations from the database and extract keys

runs:
  using: composite
  steps:
    - name: Pull translations
      run: yarn i18n:pull
      env:
        DATABASE_HOST: ${{ vars.DATABASE_HOST }}
        DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      shell: bash

    - name: Extract translations keys
      run: yarn i18n:extract
      shell: bash

   