name: Pull translations
description: Pull translations from the database and extract keys

inputs:
  database-host:
    description: Hostname of the database
    required: true
  database-username:
    description: Username of the database
    required: true
  database-password:
    description: Password of the database
    required: true


runs:
  using: composite
  steps:
    - name: Pull translations
      run: yarn i18n:pull
      env:
        DATABASE_HOST: ${{ inputs.database-host }}
        DATABASE_USERNAME: ${{ inputs.database-username }}
        DATABASE_PASSWORD: ${{ inputs.database-password }}
      shell: bash

    - name: Extract translations keys
      run: yarn i18n:extract
      shell: bash

   