name: Pull translations
description: Pull translations from the database and extract keys

inputs:
  DEPLOYMENT_ENVIRONMENT:
    description: dev, staging or production
    required: true
  API_SERVER_TOKEN:
    description: token to call translations api
    required: true
  TRANSLATION_APP_API_ENDPOINT:
    description: endpoint of the translations api
    required: true


runs:
  using: composite
  steps:
    - name: Extract translations keys
      run: yarn i18n:extract
      shell: bash
    - name: Pull translations
      run: yarn i18n:pull
      env:
        DEPLOYMENT_ENVIRONMENT: ${{ inputs.DEPLOYMENT_ENVIRONMENT }}
        API_SERVER_TOKEN: ${{ inputs.API_SERVER_TOKEN }}
        TRANSLATION_APP_API_ENDPOINT: ${{ inputs.TRANSLATION_APP_API_ENDPOINT }}
      shell: bash

 

   