name: Test
on: pull_request
jobs:
  continuous-integration :
    name: Validate and test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          
      - run: yarn install --frozen-lockfile

      - uses: ruby/setup-ruby@v1
        with:
          working-directory: packages/app
          bundler-cache: true

      # JavaScript build
      - name: Relay Compiler 
        run: yarn build
      
      # Testing
      - name: JavaScript build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn typecheck

      - name: Test
        run: yarn test
