name: CI process on pull request on release branch
on: 
  pull_request:
    branches:
      - main
      - staging
      - production
jobs:
  continuous-integration :
    name: Validate and test and Build
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{secrets.VERCEL_TOKEN}}
      TURBO_TEAM: azzapp
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          
      - run: yarn install --frozen-lockfile

      - uses: ruby/setup-ruby@v1
        with:
          working-directory: packages/app
          bundler-cache: true

      # Testing
      - name: JavaScript build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn typecheck

      - name: Test
        run: yarn test
