name: PlanetScale Merge Deploy Request on GH PR merge
on:
  pull_request:
    branches:
      - main
      - staging
    types: [closed]
   
env:
  pscale_base_directory: .pscale

jobs:
  merge_planetscale_pr:
    if: github.event.pull_request.merged == true
    name: Merge PR on planetscale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the current branch name lowercase without dashes
        shell: bash
        run: echo "BRANCH_NAME=$(echo $GITHUB_HEAD_REF | tr "[:upper:]" "[:lower:]" | sed -e 's/-//g')" >> $GITHUB_OUTPUT
        id: branch_name    

      - name: Find planetScale open deploy request if exist 
        id: get-pr-info
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
          PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
          ORG_NAME: ${{secrets.ORG_NAME}}
          DB_NAME: ${{secrets.DB_NAME}}
          GITHUB_USER: ${{github.actor}}
          BRANCH_NAME: ${{ steps.branch_name.outputs.BRANCH_NAME }-pr
        run: |
          ./retrieve-pullrequest-info.sh "$BRANCH_NAME" "$DB_NAME" "$ORG_NAME"   
    
      
      - name: Merging schema changes - if asked, please click on displayed link to authenticate
        id: merge-dr
        timeout-minutes: 10
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
          PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
          GITHUB_USER: ${{github.actor}}
          ORG_NAME: ${{secrets.ORG_NAME}}
          DB_NAME: ${{secrets.DB_NAME}}
          BRANCH_NAME: ${{ steps.branch_name.outputs.BRANCH_NAME }-pr
          DEPLOY_REQUEST_NUMBER: ${{ steps.get-pr-info.outputs.DEPLOY_REQUEST_NUMBER }}
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        run: |
          ./merge-deploy-request.sh $DEPLOY_REQUEST_NUMBER