name: Create PlanetScale DB branch and deploy request
on:
  pull_request:
    branches:
      - staging
      - production
env:
  pscale_base_directory: .pscale
jobs:
  planetscale_create-pr:
    if: github.event.pull_request.merged != true 
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if schema.prisma file changed in PR
        id: changed-files
        uses: tj-actions/changed-files@v35.5.0
        with:
          files: |
            packages/data/prisma/schema.prisma

      - name: Get the current branch name lowercase without dashes
        shell: bash
        run: echo "BRANCH_NAME=$(echo $GITHUB_HEAD_REF | tr "[:upper:]" "[:lower:]" | sed -e 's/-//g')" >> $GITHUB_OUTPUT
        id: branch_name

      - name: Create DB branch and deploy request
        if: steps.changed-files.outputs.any_changed == 'true'
        id: create-db-branch-and-dr
        timeout-minutes: 3
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
          PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
          ORG_NAME: ${{secrets.ORG_NAME}}
          DB_NAME: ${{secrets.DB_NAME}}
          GITHUB_USER: ${{github.actor}}
          BRANCH_NAME: ${{ steps.branch_name.outputs.BRANCH_NAME }}
          FROM_BRANCH: ${{ github.base_ref }}
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        run: |
          ./create-db-branch-dr-and-connection.sh "$BRANCH_NAME" "$FROM_BRANCH"

      - name: Create the prisma .env file for pushing the schema
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo "DATABASE_URL='${{ steps.create-db-branch-and-dr.outputs.CONNECT_STRING }}${{secrets.DB_NAME}}?sslaccept=strict'" > packages/data/.env

      - name: Yarn install
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn install --frozen-lockfile  --immutable

      - name: Push schema changes
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: packages/data
        run: yarn prisma db push

      - name: Get Planetscale Pull request info
        if: steps.changed-files.outputs.any_changed == 'true'
        id: get-pr-info
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
          PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
          ORG_NAME: ${{secrets.ORG_NAME}}
          DB_NAME: ${{secrets.DB_NAME}}
          GITHUB_USER: ${{github.actor}}
          BRANCH_NAME: ${{ steps.branch_name.outputs.BRANCH_NAME }}
        run: |
          echo ${{ steps.create-db-branch-and-dr.outputs.DEPLOY_REQUEST_NUMBER }}
          ./retrieve-deploy-diff-pull-request.sh ${{ steps.create-db-branch-and-dr.outputs.DEPLOY_REQUEST_NUMBER }} "$BRANCH_NAME" "$DB_NAME" "$ORG_NAME" 

      - uses: mshick/add-pr-comment@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          message: |
            This PR contains the database change needed to go along with the PR:

             * :seedling: __DB-Branch__: [${{ steps.create-db-branch-and-dr.outputs.branch_name }}](${{ steps.create-db-branch-and-dr.outputs.BRANCH_URL }})

             * :train2: __Deploy-Request URL__: ${{ steps.create-db-branch-and-dr.outputs.DEPLOY_REQUEST_URL }}

             * :lock: __Branch connection info__: [One-time link](${{ steps.create-db-branch-and-dr.outputs.CONNECTION_STRING_LINK }})

             <details>
             <summary>:computer: pscale CLI commands for local access</summary>


             ```

             pscale shell "${{ steps.create-db-branch-and-dr.outputs.DB_NAME }}" "${{ steps.create-db-branch-and-dr.outputs.BRANCH_NAME }}" --org "${{ steps.create-db-branch-and-dr.outputs.ORG_NAME }}"

             pscale connect "${{ steps.create-db-branch-and-dr.outputs.DB_NAME }}" "${{ steps.create-db-branch-and-dr.outputs.BRANCH_NAME }}" --org "${{ steps.create-db-branch-and-dr.outputs.ORG_NAME }}"   
             
             ```

             </details>

             
             <details>
             <summary>📖 Calculated schema changes:</summary>


             ```diff

             ${{ steps.get-pr-info.outputs.BRANCH_DIFF }}
             ```
             
             </details>
             
             
             If you are ok with the schema changes and have carefully reviewed them, you can merge them with a `/ps-merge` comment or it will be merge automatically in pull request close.
