name: Pull Request - Test and Build JavaScript code
on: 
  pull_request:
    branches:
      - main
      - staging
      - stable
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true  
jobs:
  continuous-integration :
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{secrets.VERCEL_TOKEN}}
      TURBO_TEAM: azzapp
      NODE_OPTIONS: --max-old-space-size=4096
      PAYMENT_API_URL: ${{ vars.PAYMENT_API_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup 

      - name: Build translations
        run: yarn i18n:extract

      - name: JavaScript build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn typecheck

      - name: Test
        run: yarn test
