name: Release
on:
  workflow_dispatch:
jobs:
  release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    environment: ${{(github.ref_name == 'stable' && 'Production') || (github.ref_name == 'staging' && 'Staging') || 'Development' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Git config
        run: |
          git config user.name "Azzapp Dev Bot"
          git config user.email "azzapp-dev-bot@azzapp.com"

      - name: Release
        run: |
          > CHANGELOG.md
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            yarn release --prerelease
          else
            yarn release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
