name: rerieve secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        APPCENTER_DEV_IOS_API_TOKEN: ${{ secrets.APPCENTER_DEV_IOS_API_TOKEN }}
        APPCENTER_DEV_IOS_APP_NAME: ${{ secrets.APPCENTER_DEV_IOS_APP_NAME }}
        APPCENTER_DEV_IOS_APP_SECRET: ${{ secrets.APPCENTER_DEV_IOS_APP_SECRET }}
        APPCENTER_STAGING_IOS_API_TOKEN: ${{ secrets.APPCENTER_STAGING_IOS_API_TOKEN }}
        APPCENTER_STAGING_IOS_APP_NAME: ${{ secrets.APPCENTER_STAGING_IOS_APP_NAME }}
        APPCENTER_STAGING_IOS_APP_SECRET: ${{ secrets.APPCENTER_STAGING_IOS_APP_SECRET }}
        FASTLANE_APPSTORE_API_KEY: ${{ secrets.FASTLANE_APPSTORE_API_KEY }}
        FASTLANE_GIT_BASIC_AUTH: ${{ secrets.FASTLANE_GIT_BASIC_AUTH }}
        FASTLANE_MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        echo APPCENTER_DEV_IOS_API_TOKEN=$APPCENTER_DEV_IOS_API_TOKEN >> secrets.txt
        echo APPCENTER_DEV_IOS_APP_NAME=$APPCENTER_DEV_IOS_APP_NAME >> secrets.txt
        echo APPCENTER_DEV_IOS_APP_SECRET=$APPCENTER_DEV_IOS_APP_SECRET >> secrets.txt
        echo APPCENTER_STAGING_IOS_API_TOKEN=$APPCENTER_STAGING_IOS_API_TOKEN >> secrets.txt
        echo APPCENTER_STAGING_IOS_APP_NAME=$APPCENTER_STAGING_IOS_APP_NAME >> secrets.txt
        echo APPCENTER_STAGING_IOS_APP_SECRET=$APPCENTER_STAGING_IOS_APP_SECRET >> secrets.txt
        echo FASTLANE_APPSTORE_API_KEY=$FASTLANE_APPSTORE_API_KEY >> secrets.txt
        echo FASTLANE_GIT_BASIC_AUTH=$FASTLANE_GIT_BASIC_AUTH >> secrets.txt
        echo FASTLANE_MATCH_PASSWORD=$FASTLANE_MATCH_PASSWORD >> secrets.txt
        echo VERCEL_TOKEN=$VERCEL_TOKEN >> secrets.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: secrets.txt
