import Foundation

// Country data model
struct Country: Identifiable, Hashable {
  let id = UUID()
  let name: String
  let code: String
  let flag: String
  let regionCode: String  // ISO 3166-1 alpha-2 country code
}

// Complete country list with flags and calling codes

let countries: [Country] = [
  Country(name: "Afghanistan", code: "+93", flag: "🇦🇫", regionCode: "AF"),
  Country(name: "Albania", code: "+355", flag: "🇦🇱", regionCode: "AL"),
  Country(name: "Algeria", code: "+213", flag: "🇩🇿", regionCode: "DZ"),
  Country(name: "Andorra", code: "+376", flag: "🇦🇩", regionCode: "AD"),
  Country(name: "Angola", code: "+244", flag: "🇦🇴", regionCode: "AO"),
  Country(name: "Antigua and Barbuda", code: "+1", flag: "🇦🇬", regionCode: "AG"),
  Country(name: "Argentina", code: "+54", flag: "🇦🇷", regionCode: "AR"),
  Country(name: "Armenia", code: "+374", flag: "🇦🇲", regionCode: "AM"),
  Country(name: "Australia", code: "+61", flag: "🇦🇺", regionCode: "AU"),
  Country(name: "Austria", code: "+43", flag: "🇦🇹", regionCode: "AT"),
  Country(name: "Azerbaijan", code: "+994", flag: "🇦🇿", regionCode: "AZ"),
  Country(name: "Bahamas", code: "+1", flag: "🇧🇸", regionCode: "BS"),
  Country(name: "Bahrain", code: "+973", flag: "🇧🇭", regionCode: "BH"),
  Country(name: "Bangladesh", code: "+880", flag: "🇧🇩", regionCode: "BD"),
  Country(name: "Barbados", code: "+1", flag: "🇧🇧", regionCode: "BB"),
  Country(name: "Belarus", code: "+375", flag: "🇧🇾", regionCode: "BY"),
  Country(name: "Belgium", code: "+32", flag: "🇧🇪", regionCode: "BE"),
  Country(name: "Belize", code: "+501", flag: "🇧🇿", regionCode: "BZ"),
  Country(name: "Benin", code: "+229", flag: "🇧🇯", regionCode: "BJ"),
  Country(name: "Bhutan", code: "+975", flag: "🇧🇹", regionCode: "BT"),
  Country(name: "Bolivia", code: "+591", flag: "🇧🇴", regionCode: "BO"),
  Country(name: "Bosnia and Herzegovina", code: "+387", flag: "🇧🇦", regionCode: "BA"),
  Country(name: "Botswana", code: "+267", flag: "🇧🇼", regionCode: "BW"),
  Country(name: "Brazil", code: "+55", flag: "🇧🇷", regionCode: "BR"),
  Country(name: "Brunei", code: "+673", flag: "🇧🇳", regionCode: "BN"),
  Country(name: "Bulgaria", code: "+359", flag: "🇧🇬", regionCode: "BG"),
  Country(name: "Burkina Faso", code: "+226", flag: "🇧🇫", regionCode: "BF"),
  Country(name: "Burundi", code: "+257", flag: "🇧🇮", regionCode: "BI"),
  Country(name: "Cambodia", code: "+855", flag: "🇰🇭", regionCode: "KH"),
  Country(name: "Cameroon", code: "+237", flag: "🇨🇲", regionCode: "CM"),
  Country(name: "Canada", code: "+1", flag: "🇨🇦", regionCode: "CA"),
  Country(name: "Cape Verde", code: "+238", flag: "🇨🇻", regionCode: "CV"),
  Country(name: "Central African Republic", code: "+236", flag: "🇨🇫", regionCode: "CF"),
  Country(name: "Chad", code: "+235", flag: "🇹🇩", regionCode: "TD"),
  Country(name: "Chile", code: "+56", flag: "🇨🇱", regionCode: "CL"),
  Country(name: "China", code: "+86", flag: "🇨🇳", regionCode: "CN"),
  Country(name: "Colombia", code: "+57", flag: "🇨🇴", regionCode: "CO"),
  Country(name: "Comoros", code: "+269", flag: "🇰🇲", regionCode: "KM"),
  Country(name: "Congo", code: "+242", flag: "🇨🇬", regionCode: "CG"),
  Country(name: "Costa Rica", code: "+506", flag: "🇨🇷", regionCode: "CR"),
  Country(name: "Croatia", code: "+385", flag: "🇭🇷", regionCode: "HR"),
  Country(name: "Cuba", code: "+53", flag: "🇨🇺", regionCode: "CU"),
  Country(name: "Cyprus", code: "+357", flag: "🇨🇾", regionCode: "CY"),
  Country(name: "Czech Republic", code: "+420", flag: "🇨🇿", regionCode: "CZ"),
  Country(name: "Denmark", code: "+45", flag: "🇩🇰", regionCode: "DK"),
  Country(name: "Djibouti", code: "+253", flag: "🇩🇯", regionCode: "DJ"),
  Country(name: "Dominica", code: "+1", flag: "🇩🇲", regionCode: "DM"),
  Country(name: "Dominican Republic", code: "+1", flag: "🇩🇴", regionCode: "DO"),
  Country(name: "Ecuador", code: "+593", flag: "🇪🇨", regionCode: "EC"),
  Country(name: "Egypt", code: "+20", flag: "🇪🇬", regionCode: "EG"),
  Country(name: "El Salvador", code: "+503", flag: "🇸🇻", regionCode: "SV"),
  Country(name: "Equatorial Guinea", code: "+240", flag: "🇬🇶", regionCode: "GQ"),
  Country(name: "Eritrea", code: "+291", flag: "🇪🇷", regionCode: "ER"),
  Country(name: "Estonia", code: "+372", flag: "🇪🇪", regionCode: "EE"),
  Country(name: "Ethiopia", code: "+251", flag: "🇪🇹", regionCode: "ET"),
  Country(name: "Fiji", code: "+679", flag: "🇫🇯", regionCode: "FJ"),
  Country(name: "Finland", code: "+358", flag: "🇫🇮", regionCode: "FI"),
  Country(name: "France", code: "+33", flag: "🇫🇷", regionCode: "FR"),
  Country(name: "Gabon", code: "+241", flag: "🇬🇦", regionCode: "GA"),
  Country(name: "Gambia", code: "+220", flag: "🇬🇲", regionCode: "GM"),
  Country(name: "Georgia", code: "+995", flag: "🇬🇪", regionCode: "GE"),
  Country(name: "Germany", code: "+49", flag: "🇩🇪", regionCode: "DE"),
  Country(name: "Ghana", code: "+233", flag: "🇬🇭", regionCode: "GH"),
  Country(name: "Greece", code: "+30", flag: "🇬🇷", regionCode: "GR"),
  Country(name: "Grenada", code: "+1", flag: "🇬🇩", regionCode: "GD"),
  Country(name: "Guatemala", code: "+502", flag: "🇬🇹", regionCode: "GT"),
  Country(name: "Guinea", code: "+224", flag: "🇬🇳", regionCode: "GN"),
  Country(name: "Guinea-Bissau", code: "+245", flag: "🇬🇼", regionCode: "GW"),
  Country(name: "Guyana", code: "+592", flag: "🇬🇾", regionCode: "GY"),
  Country(name: "Haiti", code: "+509", flag: "🇭🇹", regionCode: "HT"),
  Country(name: "Honduras", code: "+504", flag: "🇭🇳", regionCode: "HN"),
  Country(name: "Hungary", code: "+36", flag: "🇭🇺", regionCode: "HU"),
  Country(name: "Iceland", code: "+354", flag: "🇮🇸", regionCode: "IS"),
  Country(name: "India", code: "+91", flag: "🇮🇳", regionCode: "IN"),
  Country(name: "Indonesia", code: "+62", flag: "🇮🇩", regionCode: "ID"),
  Country(name: "Iran", code: "+98", flag: "🇮🇷", regionCode: "IR"),
  Country(name: "Iraq", code: "+964", flag: "🇮🇶", regionCode: "IQ"),
  Country(name: "Ireland", code: "+353", flag: "🇮🇪", regionCode: "IE"),
  Country(name: "Israel", code: "+972", flag: "🇮🇱", regionCode: "IL"),
  Country(name: "Italy", code: "+39", flag: "🇮🇹", regionCode: "IT"),
  Country(name: "Jamaica", code: "+1", flag: "🇯🇲", regionCode: "JM"),
  Country(name: "Japan", code: "+81", flag: "🇯🇵", regionCode: "JP"),
  Country(name: "Jordan", code: "+962", flag: "🇯🇴", regionCode: "JO"),
  Country(name: "Kazakhstan", code: "+7", flag: "🇰🇿", regionCode: "KZ"),
  Country(name: "Kenya", code: "+254", flag: "🇰🇪", regionCode: "KE"),
  Country(name: "Kiribati", code: "+686", flag: "🇰🇮", regionCode: "KI"),
  Country(name: "Kuwait", code: "+965", flag: "🇰🇼", regionCode: "KW"),
  Country(name: "Kyrgyzstan", code: "+996", flag: "🇰🇬", regionCode: "KG"),
  Country(name: "Laos", code: "+856", flag: "🇱🇦", regionCode: "LA"),
  Country(name: "Latvia", code: "+371", flag: "🇱🇻", regionCode: "LV"),
  Country(name: "Lebanon", code: "+961", flag: "🇱🇧", regionCode: "LB"),
  Country(name: "Lesotho", code: "+266", flag: "🇱🇸", regionCode: "LS"),
  Country(name: "Liberia", code: "+231", flag: "🇱🇷", regionCode: "LR"),
  Country(name: "Libya", code: "+218", flag: "🇱🇾", regionCode: "LY"),
  Country(name: "Liechtenstein", code: "+423", flag: "🇱🇮", regionCode: "LI"),
  Country(name: "Lithuania", code: "+370", flag: "🇱🇹", regionCode: "LT"),
  Country(name: "Luxembourg", code: "+352", flag: "🇱🇺", regionCode: "LU"),
  Country(name: "Madagascar", code: "+261", flag: "🇲🇬", regionCode: "MG"),
  Country(name: "Malawi", code: "+265", flag: "🇲🇼", regionCode: "MW"),
  Country(name: "Malaysia", code: "+60", flag: "🇲🇾", regionCode: "MY"),
  Country(name: "Maldives", code: "+960", flag: "🇲🇻", regionCode: "MV"),
  Country(name: "Mali", code: "+223", flag: "🇲🇱", regionCode: "ML"),
  Country(name: "Malta", code: "+356", flag: "🇲🇹", regionCode: "MT"),
  Country(name: "Marshall Islands", code: "+692", flag: "🇲🇭", regionCode: "MH"),
  Country(name: "Mauritania", code: "+222", flag: "🇲🇷", regionCode: "MR"),
  Country(name: "Mauritius", code: "+230", flag: "🇲🇺", regionCode: "MU"),
  Country(name: "Mexico", code: "+52", flag: "🇲🇽", regionCode: "MX"),
  Country(name: "Micronesia", code: "+691", flag: "🇫🇲", regionCode: "FM"),
  Country(name: "Moldova", code: "+373", flag: "🇲🇩", regionCode: "MD"),
  Country(name: "Monaco", code: "+377", flag: "🇲🇨", regionCode: "MC"),
  Country(name: "Mongolia", code: "+976", flag: "🇲🇳", regionCode: "MN"),
  Country(name: "Montenegro", code: "+382", flag: "🇲🇪", regionCode: "ME"),
  Country(name: "Morocco", code: "+212", flag: "🇲🇦", regionCode: "MA"),
  Country(name: "Mozambique", code: "+258", flag: "🇲🇿", regionCode: "MZ"),
  Country(name: "Myanmar", code: "+95", flag: "🇲🇲", regionCode: "MM"),
  Country(name: "Namibia", code: "+264", flag: "🇳🇦", regionCode: "NA"),
  Country(name: "Nauru", code: "+674", flag: "🇳🇷", regionCode: "NR"),
  Country(name: "Nepal", code: "+977", flag: "🇳🇵", regionCode: "NP"),
  Country(name: "Netherlands", code: "+31", flag: "🇳🇱", regionCode: "NL"),
  Country(name: "New Zealand", code: "+64", flag: "🇳🇿", regionCode: "NZ"),
  Country(name: "Nicaragua", code: "+505", flag: "🇳🇮", regionCode: "NI"),
  Country(name: "Niger", code: "+227", flag: "🇳🇪", regionCode: "NE"),
  Country(name: "Nigeria", code: "+234", flag: "🇳🇬", regionCode: "NG"),
  Country(name: "North Korea", code: "+850", flag: "🇰🇵", regionCode: "KP"),
  Country(name: "North Macedonia", code: "+389", flag: "🇲🇰", regionCode: "MK"),
  Country(name: "Norway", code: "+47", flag: "🇳🇴", regionCode: "NO"),
  Country(name: "Oman", code: "+968", flag: "🇴🇲", regionCode: "OM"),
  Country(name: "Pakistan", code: "+92", flag: "🇵🇰", regionCode: "PK"),
  Country(name: "Palau", code: "+680", flag: "🇵🇼", regionCode: "PW"),
  Country(name: "Palestine", code: "+970", flag: "🇵🇸", regionCode: "PS"),
  Country(name: "Panama", code: "+507", flag: "🇵🇦", regionCode: "PA"),
  Country(name: "Papua New Guinea", code: "+675", flag: "🇵🇬", regionCode: "PG"),
  Country(name: "Paraguay", code: "+595", flag: "🇵🇾", regionCode: "PY"),
  Country(name: "Peru", code: "+51", flag: "🇵🇪", regionCode: "PE"),
  Country(name: "Philippines", code: "+63", flag: "🇵🇭", regionCode: "PH"),
  Country(name: "Poland", code: "+48", flag: "🇵🇱", regionCode: "PL"),
  Country(name: "Portugal", code: "+351", flag: "🇵🇹", regionCode: "PT"),
  Country(name: "Qatar", code: "+974", flag: "🇶🇦", regionCode: "QA"),
  Country(name: "Romania", code: "+40", flag: "🇷🇴", regionCode: "RO"),
  Country(name: "Russia", code: "+7", flag: "🇷🇺", regionCode: "RU"),
  Country(name: "Rwanda", code: "+250", flag: "🇷🇼", regionCode: "RW"),
  Country(name: "Saint Kitts and Nevis", code: "+1", flag: "🇰🇳", regionCode: "KN"),
  Country(name: "Saint Lucia", code: "+1", flag: "🇱🇨", regionCode: "LC"),
  Country(name: "Saint Vincent and the Grenadines", code: "+1", flag: "🇻🇨", regionCode: "VC"),
  Country(name: "Samoa", code: "+685", flag: "🇼🇸", regionCode: "WS"),
  Country(name: "San Marino", code: "+378", flag: "🇸🇲", regionCode: "SM"),
  Country(name: "Sao Tome and Principe", code: "+239", flag: "🇸🇹", regionCode: "ST"),
  Country(name: "Saudi Arabia", code: "+966", flag: "🇸🇦", regionCode: "SA"),
  Country(name: "Senegal", code: "+221", flag: "🇸🇳", regionCode: "SN"),
  Country(name: "Serbia", code: "+381", flag: "🇷🇸", regionCode: "RS"),
  Country(name: "Seychelles", code: "+248", flag: "🇸🇨", regionCode: "SC"),
  Country(name: "Sierra Leone", code: "+232", flag: "🇸🇱", regionCode: "SL"),
  Country(name: "Singapore", code: "+65", flag: "🇸🇬", regionCode: "SG"),
  Country(name: "Slovakia", code: "+421", flag: "🇸🇰", regionCode: "SK"),
  Country(name: "Slovenia", code: "+386", flag: "🇸🇮", regionCode: "SI"),
  Country(name: "Solomon Islands", code: "+677", flag: "🇸🇧", regionCode: "SB"),
  Country(name: "Somalia", code: "+252", flag: "🇸🇴", regionCode: "SO"),
  Country(name: "South Africa", code: "+27", flag: "🇿🇦", regionCode: "ZA"),
  Country(name: "South Korea", code: "+82", flag: "🇰🇷", regionCode: "KR"),
  Country(name: "South Sudan", code: "+211", flag: "🇸🇸", regionCode: "SS"),
  Country(name: "Spain", code: "+34", flag: "🇪🇸", regionCode: "ES"),
  Country(name: "Sri Lanka", code: "+94", flag: "🇱🇰", regionCode: "LK"),
  Country(name: "Sudan", code: "+249", flag: "🇸🇩", regionCode: "SD"),
  Country(name: "Suriname", code: "+597", flag: "🇸🇷", regionCode: "SR"),
  Country(name: "Sweden", code: "+46", flag: "🇸🇪", regionCode: "SE"),
  Country(name: "Switzerland", code: "+41", flag: "🇨🇭", regionCode: "CH"),
  Country(name: "Syria", code: "+963", flag: "🇸🇾", regionCode: "SY"),
  Country(name: "Taiwan", code: "+886", flag: "🇹🇼", regionCode: "TW"),
  Country(name: "Tajikistan", code: "+992", flag: "🇹🇯", regionCode: "TJ"),
  Country(name: "Tanzania", code: "+255", flag: "🇹🇿", regionCode: "TZ"),
  Country(name: "Thailand", code: "+66", flag: "🇹🇭", regionCode: "TH"),
  Country(name: "Timor-Leste", code: "+670", flag: "🇹🇱", regionCode: "TL"),
  Country(name: "Togo", code: "+228", flag: "🇹🇬", regionCode: "TG"),
  Country(name: "Tonga", code: "+676", flag: "🇹🇴", regionCode: "TO"),
  Country(name: "Trinidad and Tobago", code: "+1", flag: "🇹🇹", regionCode: "TT"),
  Country(name: "Tunisia", code: "+216", flag: "🇹🇳", regionCode: "TN"),
  Country(name: "Turkey", code: "+90", flag: "🇹🇷", regionCode: "TR"),
  Country(name: "Turkmenistan", code: "+993", flag: "🇹🇲", regionCode: "TM"),
  Country(name: "Tuvalu", code: "+688", flag: "🇹🇻", regionCode: "TV"),
  Country(name: "Uganda", code: "+256", flag: "🇺🇬", regionCode: "UG"),
  Country(name: "Ukraine", code: "+380", flag: "🇺🇦", regionCode: "UA"),
  Country(name: "United Arab Emirates", code: "+971", flag: "🇦🇪", regionCode: "AE"),
  Country(name: "United Kingdom", code: "+44", flag: "🇬🇧", regionCode: "GB"),
  Country(name: "United States", code: "+1", flag: "🇺🇸", regionCode: "US"),
  Country(name: "Uruguay", code: "+598", flag: "🇺🇾", regionCode: "UY"),
  Country(name: "Uzbekistan", code: "+998", flag: "🇺🇿", regionCode: "UZ"),
  Country(name: "Vanuatu", code: "+678", flag: "🇻🇺", regionCode: "VU"),
  Country(name: "Vatican City", code: "+379", flag: "🇻🇦", regionCode: "VA"),
  Country(name: "Venezuela", code: "+58", flag: "🇻🇪", regionCode: "VE"),
  Country(name: "Vietnam", code: "+84", flag: "🇻🇳", regionCode: "VN"),
  Country(name: "Yemen", code: "+967", flag: "🇾🇪", regionCode: "YE"),
  Country(name: "Zambia", code: "+260", flag: "🇿🇲", regionCode: "ZM"),
  Country(name: "Zimbabwe", code: "+263", flag: "🇿🇼", regionCode: "ZW"),
]
